#ifndef GOLANGEDITOR_GLOBAL_H
#define GOLANGEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SYNTAXEDITOR_LIBRARY)
#  define SYNTAXEDITORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SYNTAXEDITORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GOLANGEDITOR_GLOBAL_H
